name: dl1
channels:
    - conda-forge
    - defaults
    - pytorch
    - nvidia
dependencies:
    - conda-forge::ipywidgets
    - conda-forge::jupyterlab
    - conda-forge::matplotlib
    - conda-forge::tqdm
    - nvidia::cudatoolkit=11.3
    - pytorch::pytorch=1.10
    - pytorch::torchvision
